import Capacitor
import UIKit

/// Root bridge view controller for the `App` target — set as the
/// `Main.storyboard` initial view controller in place of the bare
/// `CAPBridgeViewController`.
///
/// Why this exists (issue #175, PRD #56 slice 4): Capacitor 8 only
/// instantiates the plugin classes listed in `capacitor.config.json`'s
/// `packageClassList`. That file is gitignored and regenerated by
/// `npx cap sync ios` (run in CI — `ios/App/App/ci_scripts/ci_post_clone.sh`)
/// from the installed npm `@capacitor/*` packages, so a hand-written, non-npm
/// Swift plugin like `EmailWidgetBridgePlugin` never lands there and is never
/// registered. Capacitor 8 dropped the Objective-C `CAP_PLUGIN` macro scan, so
/// compiling the file into the target is necessary but NOT sufficient.
///
/// Registering the instance here in `capacitorDidLoad()` — the supported hook,
/// called right after the bridge is created (`CAPBridgeViewController`) — is the
/// durable way to wire a local plugin into the bridge. Without it,
/// `registerPlugin("EmailWidgetBridge")` on the web side resolves to the no-op
/// web proxy, `writeEmailSummary` rejects "not implemented", and nothing is
/// ever written to the App Group the Emails widget reads.
class MainViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        bridge?.registerPluginInstance(EmailWidgetBridgePlugin())
    }
}
